### ISSUE TITLE
Radio Buttons/Checkbox values with val() Method not working as expected

### ISSUE THREAD

**Issue by warhuhn** [PerryRylance/DOMDocument#43]
I expected the val() Method to work like jQuery.
However, checking the value for Radio button or Checkbox inputs returns "true" or "false", depending on the checked Attribute.

jQuery returns the contents of the value Field.

```html
<input type="radio" name="fuel_type" value="gas" checked> Gasoline<br>
<input type="radio" name="fuel_type" value="diesel"> Diesel
```

```php
<?php

// ...

/** @var \PerryRylance\DOMDocument $dom */

$value = $dom->find('input:checked')->val();

// actual: true
// expected: 'gas'
```

The method should return the value of the "value" Attribute.

**Comment by PerryRylance** [comment]
This will be solved in 2.0.2, commit coming shortly
